- src/ValidationError.js
- test/index.test.js
- adds `err.name` (`ValidationError`)
- handle `err.stack` via `Error.captureStackTrace`
> fix(ValidationError): use `Error.captureStackTrace` for `err.stack` handling

- package-lock.json
- package.json
> chore(package): update `ajv` v5.0.0...v6.1.0 && `ajv-keywords` v2.1.0...v3.1.0 (`dependencies`)

- src/ValidationError.js
- test/__snapshots__/index.test.js.snap
fix undefined in message
No
No
> fix: `minItems` error message

- src/index.js
- test/api.test.js
> feat: export `ValidateError`

- .github/CONTRIBUTING.md
- package-lock.json
- package.json
update deps and fix invalid links
No
No
> chore(deps): update

- test/api.test.js
> test: more

- package.json
We need to publish definitions
> fix: publish definitions

- index.d.ts
- src/index.js
- test/api.test.js
Use original name - `ValidationError`
Also run prettier on this file
No, keep old name too
No
> fix: typescript and naming

- package-lock.json
- package.json
> chore: improve build pipeline

- azure-pipelines.yml
setup linting for declarations
No
No
fixes #74
> ci: lint declarations

- azure-pipelines.yml
Features:
- Cache npm
- Use latest vm images
- node@13 test
No
No
> ci: improve

- .editorconfig
- .gitignore
- azure-pipelines.yml
- lint-staged.config.js
- package-lock.json
- package.json
> chore(defaults): update

- declarations/validate.d.ts
- src/index.js
- src/validate.js
fix buggy declaration from typescript
No
No
> fix: typescript declarations

- package-lock.json
- package.json
- src/ValidationError.js
- test/__snapshots__/api.test.js.snap
prefer the `baseDataPath` option from arguments
No
No
> fix: prefer the `baseDataPath` option from arguments

- src/ValidationError.js
- test/__snapshots__/api.test.js.snap
- test/__snapshots__/index.test.js.snap
change initialised to initialized to be US english instead of British english
No
No
> fix: change `initialised` to `initialized`

- README.md
> [Docs]: Minor tweaks

- declarations/keywords/absolutePath.d.ts
- declarations/util/Range.d.ts
- declarations/validate.d.ts
- package-lock.json
- package.json
- src/ValidationError.js
- src/keywords/absolutePath.js
- test/__snapshots__/index.test.js.snap
No duplicate `.` when description already contains a dot.
no
> remove dot as description usually already contains a dot

- package-lock.json
- package.json
> fix: npm audit fix

- package-lock.json
- src/validate.js
- Decreasing of time complexity
- Decreasing of memory complexity
1. Removed usage of map in order to reduce number of memory allocations.
2. Replaced concat with push in order to change complexity from O(n^2) to O(n)
> perf(validate): improvement of time and memory complexity of validate

- .github/ISSUE_TEMPLATE.md
> chore: fix typo in ISSUE_TEMPLATE

- package-lock.json
- package.json
- test/index.test.js
update tests + update deps
No
No
> chore: deps and tests

- .eslintrc.js
- .prettierrc.js
- README.md
- babel.config.js
- commitlint.config.js
- declarations/ValidationError.d.ts
- declarations/index.d.ts
- declarations/keywords/absolutePath.d.ts
- declarations/util/Range.d.ts
- declarations/util/hints.d.ts
- declarations/validate.d.ts
- lint-staged.config.js
- src/ValidationError.js
- src/index.js
- src/keywords/absolutePath.js
- src/util/Range.js
- src/util/hints.js
- src/validate.js
- test/api.test.js
- test/hints.test.js
- test/index.test.js
- test/range.test.js
Update prettier config.
None
No
> chore: update prettier config

- declarations/validate.d.ts
- src/ValidationError.js
- src/validate.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/schema.json
Imporve error message.
Maybe
No
> feat: show link in validation error

- .github/workflows/nodejs.yml
> chore: update commitlint github action to v4

- .github/workflows/nodejs.yml
> ci: use node v16

- lint-staged.config.js
update `lint-staged` config.
None
None
> chore: update `lint-staged` config

- .github/workflows/nodejs.yml
remove install NPM step
none
No
> ci: remove install NPM step

- .github/ISSUE_TEMPLATE/BUG.md
> docs: fix typo in bug report template

- .github/workflows/nodejs.yml
Use the latest version of GitHub actions.
No
No
> ci: update github actions

- README.md
> docs: remove outdated badge

- src/validate.js
> fix(perf): reduce initial start time

- README.md
> docs: add GitHub Discussions badge

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
use GitHub discussions instead of Gitter in issue templates
No
No
> docs: use GitHub discussions instead of Gitter in issue templates

- declarations/index.d.ts
- declarations/validate.d.ts
- src/index.js
- src/validate.js
- test/__snapshots__/api.test.js.snap
- test/api.test.js
API to enable/disable validation
No
Backport from v4
> feat: added API to disable and enable validation

- src/ValidationError.js
- test/__snapshots__/index.test.js.snap
- test/index.test.js
fixes #193
I'm not aware of any, at least, none of the tests failed.
No
> feat: disallow arrays as the object type

- .github/workflows/nodejs.yml
- README.md
- package.json
> chore: rename master to main
